/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import java.util.ArrayList;

import database.DataBaseHelper;
import objects.Client;

public class App {
    public static void main(String[] args) {
        DataBaseHelper db = new DataBaseHelper();
        Client c1 = new Client("toto", "toto@toto");
        ArrayList<Client> clients = new ArrayList<>();

        db.AddClient(c1);

        db.GetClient(c1);
        System.out.println(c1.get_id() + " " + c1.get_name() + " " + c1.get_mail());

        // db.DeleteClient(c1);
        // db.GetClient(c1);
        // System.out.println(c1.get_id() + " " + c1.get_name() + " " + c1.get_mail());

        // db.GetAllClient(clients);
        // for (Client client : clients) {
        // System.out.println(client.get_id() + " " + client.get_name() + " " +
        // client.get_mail());
        // }
    }
}
